---
token: 1376542034:AAEqkb5nOYYcpUNrXzVZwCTcqmgjmggs5po # changeable
cluster: mongodb+srv://login:login@cluster-k8ee1.gcp.mongodb.net/db?retryWrites=true&w=majority # changeable
adminID: 397330072 # changeable
channelID: "-1001419360985" # changeable
chatID: "-1001417224601" # changeable
colors:
- red
- green
- blue
- yellow
- dark
post_calls:
- likes
- dlikes
